%YAML:1.0

type: pose_estimation
queue_size: 1

use_vslam: 1
use_fallback: 0
update_georef: 1
th_error_georef: 1.0
overlap_max: 95
overlap_max_fallback: 30
suppress_outdated_pose_pub: 0

save_trajectory_gnss: 1
save_trajectory_visual: 1
save_frames: 0
save_keyframes: 0
save_keyframes_full: 0